### PR TITLE
Bug fix

### PR DESCRIPTION
**Pull request by jamzth**
https://wordpress.org/support/topic/bug-in-metaboxphp-on-line-52?replies=1

### CODE REVIEW

**Comment by pippinsplugins** [comment]
Hi @jamzth,

Thanks for the pull request! This will, however, need to be split up into two separate pull requests, one to fix the bug and one to add the feature.

There are a few improvements that will need to be made to the expired feature, but I can elaborate on those on the new PR.

Could you do that?

**Comment by jamzth** [comment]
Sure! Honestly, this is the first chance that I've had to do a pull request. I thought I was putting it separately, but clearly didn't. I'll get it to you. Great plugin.

**Comment by pippinsplugins** [comment]
To make them separately, create a branch for each pull request then submit from that branch.

If you're not sure how to do that, I'll be more than happy to assist.

**Comment by jamzth** [comment]
Oh, that makes sense

**Pull request closed without merging**
